name: Lint the Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7.2-alpine
        ports: ["6379:6379"]
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Run format check
        run: pnpm run lint:fix && pnpm run lint

      - name: Run unit tests
        run: pnpm run test:unit
        env:
          REDIS_URL: redis://127.0.0.1:6379

      - uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: 'chore: format'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'